param <- list(p0 = log(.1 / (1 - .1)), # density-independent prob of dispersing (logit scale)
               b1 = 0.01, # density-dependent effect on dispersal (p1.before, logit scale)
               b2 = -0.02, # density-dependent effect on dispersal (p2.before, logit scale)
               b3 = 0.03, # density-dependent effect on dispersal (p1.other.before, logit scale)
               b4 = -0.02 # density-dependent effect on dispersal (p2.other.before, logit scale) 
               ) 
